"""Smoke test for API authentication."""

import allure
import pytest

from shared.config.settings import settings
from dashboard.fixtures.auth_fixtures import _load_user
from dashboard.locators import login_locators as L
from dashboard.pages.login_page import LoginPage
from playwright.sync_api import expect


@pytest.fixture
def login_page(browser):
    """Fresh browser context with NO stored auth — opens the login page."""
    ctx = browser.new_context(
        viewport={"width": settings.browser.viewport.width,
                  "height": settings.browser.viewport.height},
        locale=settings.browser.locale,
        timezone_id=settings.browser.timezone,
    )
    p = ctx.new_page()
    p.set_default_navigation_timeout(settings.timeouts.navigation)
    p.set_default_timeout(settings.timeouts.default)
    LoginPage(p).open()
    yield p
    ctx.close()


@allure.epic("Authentication")
@allure.feature("Login Flow")
@allure.severity(allure.severity_level.CRITICAL)
@allure.title("Valid credentials log the user in and land on the dashboard")
@pytest.mark.testcase(
    component="auth",
    type="smoke, regression",
    description="Valid credentials log the user in and land on the dashboard",
    steps=(
        "1. Open the login page\n"
        "2. Fill Username field with kitchen_sapna's email\n"
        "3. Fill Password field with kitchen_sapna's password\n"
        "4. Click 'Sign In' button\n"
        "5. Verify 'Current View' marker is visible (post-login state)"
    ),
)
@pytest.mark.smoke
@pytest.mark.regression
def test_login_happy_path(login_page):
    """Valid kitchen_sapna credentials land the user past the login screen."""
    user = _load_user("kitchen_sapna")
    LoginPage(login_page).login(user["email"], user["password"])

    assert login_page.locator(L.LOGGED_IN_MARKER).is_visible(), (
        "Expected 'Current View' marker after successful login but it wasn't visible"
    )


@allure.epic("Authentication")
@allure.feature("Login Flow")
@allure.severity(allure.severity_level.NORMAL)
@allure.title("Empty fields show inline validation errors when Sign In is clicked")
@pytest.mark.testcase(
    component="auth",
    type="regression",
    description="Empty fields show inline validation errors when Sign In is clicked",
    steps=(
        "1. Open the login page\n"
        "2. Leave Username and Password fields blank\n"
        "3. Click 'Sign In' button\n"
        "4. Verify 'Please enter a valid email address' is shown under Username\n"
        "5. Verify 'Required' is shown under Password"
    ),
)
@pytest.mark.regression
def test_login_empty_fields_shows_inline_validation(login_page):
    """Clicking Sign In with empty fields shows both inline validation errors."""
    login_page.get_by_role("button", name=L.SIGN_IN_BUTTON_TEXT).click()

    expect(login_page.get_by_text("Please enter a valid email address")).to_be_visible()
    expect(login_page.get_by_text("Required")).to_be_visible()


@allure.epic("Authentication")
@allure.feature("Login Flow")
@allure.severity(allure.severity_level.NORMAL)
@allure.title("Wrong credentials show 'Incorrect username or password' popup")
@pytest.mark.testcase(
    component="auth",
    type="regression",
    description="Wrong credentials show 'Incorrect username or password' popup",
    steps=(
        "1. Open the login page\n"
        "2. Fill Username with an invalid email (e.g. abc@gmail.com)\n"
        "3. Fill Password with a wrong password\n"
        "4. Click 'Sign In' button\n"
        "5. Verify 'Incorrect username or password.' popup appears at top"
    ),
)
@pytest.mark.regression
def test_login_wrong_credentials_shows_error_popup(login_page):
    """Wrong credentials trigger the 'Incorrect username or password' popup."""
    login_page.locator(L.EMAIL_INPUT).fill("abc@gmail.com")
    login_page.locator(L.PASSWORD_INPUT).fill("wrongpassword")
    login_page.get_by_role("button", name=L.SIGN_IN_BUTTON_TEXT).click()

    expect(login_page.get_by_text("Incorrect username or password.")).to_be_visible()


@allure.epic("Authentication")
@allure.feature("API")
@allure.severity(allure.severity_level.CRITICAL)
@allure.title("Cognito API returns a valid access token for system user")
@pytest.mark.testcase(
    component="auth",
    type="regression",
    description="Validate that correct access token is generated by cognito API",
    steps=(
        "1. Load kitchen_sapna's email and password from data/users.yaml\n"
        "2. Construct the Cognito InitiateAuth POST request with x-amz-target header and body "
        "containing AuthFlow=USER_PASSWORD_AUTH, USERNAME, PASSWORD, ClientId\n"
        "3. Send the POST request to the Cognito endpoint\n"
        "4. Assert HTTP status code is 200\n"
        "5. Parse the JSON response and assert AuthenticationResult.AccessToken is present and non-empty"
    ),
)
@pytest.mark.smoke
@pytest.mark.regression
def test_can_acquire_access_token(access_token):
    """Verify we can authenticate against Cognito and get a non-empty access token."""
    assert access_token, "Failed to acquire access token from Cognito"
    assert len(access_token) > 100, f"Access token suspiciously short: {len(access_token)} chars"
